projects:
  - id: "RM43971"
    name: "WEx1"
    description: "Iron Ore particle study - Gudda Dari High Grade (6-10mm)."
    project_lead: "Robert Sok"
    start_date: "2025-01-22"
    status: "active"
    location: "Multiple Sites"
    
  - id: "RM44125"
    name: "WEx2"
    description: "Core based pilot study"
    project_lead: "Silvano Sommacal"
    start_date: "2025-02-15"
    status: "active"
    location: "Karratha, Western Australia"
    
  - id: "RM43875"
    name: "General"
    description: "Magnetite processing optimization study"
    project_lead: "Mark Knackstedt"
    start_date: "2025-01-10"
    status: "active"
    location: "Newman, Western Australia"