speed: 5000     # Much faster for demo  
start: 2025-01-22T08:00:00  # Start from beginning of data
end:   2025-07-04T10:00:00  # End at end of data (covers ~5.5 months)

broker:
  host: "localhost"
  port: 1883
  qos: 0
  retain: false

streams:
  - id: "events"
    csv: "data/events.csv"
    topic: "lab/events"
    time_col: "created_at"
    tz: "Australia/Sydney"
    schema:
      types:
        id: "str"
        operator: "str"
        severity: "str"
        text: "str"

  - id: "weights"
    csv: "data/weights.csv"
    topic: "lab/weights"
#    stream_id: "lab_weights"
    time_col: "created_at"
    tz: "Australia/Sydney"
    entity_id_col: "particle_id"
    schema:
      rename:
        measurement_id: "id"
        weight_g: "value"
      types:
        id: "str"
        particle_id: "str"
        value: "float"
        valid: "str"
        machine: "str"
    keep_cols: ["id","particle_id","ore_type","rm_number","density_bin","value","machine","valid"]

  - id: "photos"
    csv: "data/photos.csv"
    topic: "lab/photos"
#    stream_id: "lab_photos"
    time_col: "created_at"
    tz: "Australia/Sydney"
    entity_id_col: "particle_id"
    schema:
      rename:
        id:  "id"
        num_photos: "value"
      types:
        id: "str"
        particle_id: "str"
        value: "int"
        valid: "str"
        photo_url: "str"
    drop_cols: ["photo_url"]      # keep payloads small for the dashboard
    filter: "valid == 'true'"

  - id: "properties"
    csv: "data/properties.csv"
    topic: "lab/properties"
#    stream_id: "lab_properties"
    time_col: "created_at"
    tz: "Australia/Sydney"
    entity_id_col: "particle_id"
    schema:
      rename:
        id: "id"
      types:
        id: "str"
        particle_id: "str"
        ore_type: "str"
        rm_number: "str"
        density_bin: "str"

  - id: "magnetics"
    csv: "data/magnetics.csv"
    topic: "lab/magnetics"
#    stream_id: "lab_magnetics"
    time_col: "created_at"
    tz: "Australia/Sydney"
    entity_id_col: "particle_id"
    schema:
      rename:
        id: "id"
        magnetic_susceptibility: "value"
      types:
        id: "str"
        particle_id: "str"
        value: "float"
        valid: "str"

  - id: "packs"
    csv: "data/packs.csv"
    topic: "lab/packs"
#    stream_id: "lab_packs"
    time_col: "created_at"
    tz: "Australia/Sydney"
    entity_id_col: "particle_id"
    schema:
      rename:
        id: "id"
        pack_no: "pack_id"
      types:
        id: "str"
        particle_id: "str"
        pack_id: "str"
        valid: "str"
    filter: "valid != 'false'"

  - id: "density_volume"
    csv: "data/density_volume.csv"
    topic: "lab/density_volume"
#    stream_id: "lab_density_volume"
    time_col: "created_at"
    tz: "Australia/Sydney"
    entity_id_col: "particle_id"
    schema:
      rename:
        id: "id"
        density_g_per_cm3: "value"
      types:
        id: "str"
        particle_id: "str"
        value: "float"
        density_bin_g_per_cm3: "float"

#  - id: "ct_image_data"
#    csv: "data/ct_image_data.csv"
#    topic: "lab/ct_image_data"
#    stream_id: "lab_ct_image_data"
#    time_col: "created_at"
#    tz: "Australia/Sydney"
#    entity_id_col: "particle_id"
#    schema:
#      rename:
#        id: "id"
#      types:
#        id: "str"
#        particle_id: "str"
#        series_id: "str"
#        valid: "str"
